Done
iborovikov/nodejs-homework-2-rest-api pull request #1
Opened 2021-10-29 14:02 UTC by iborovikov

2021-10-30 11:07 UTC, KirillKulakow commented on routes/api/contacts.js
> +    const { error } = joiShema.validate(req.body)
используй новую схему где будет обязательно одно поле согласно ТЗ

2021-10-30 11:17 UTC, KirillKulakow commented on routes/api/contacts.js
> +    if (contact.status === 'BadRequest') {
или формируй объект со статусом, ошибкой и т.д. здесь - или формируй в самом методе (не миксуй - это плохой вариант написания кода)

2021-10-30 11:17 UTC, KirillKulakow commented on routes/api/contacts.js
> +    if (contact.status === 'Contact not found') {
тоже самое

2021-10-30 11:20 UTC, KirillKulakow commented on routes/api/contacts.js
> +        // eslint-disable-next-line no-unreachable
было бы лучше убрать switch case, ESLint тебе ошибку выводит что вызов ошибки в свиче это плохая практика

2021-10-30 13:18 UTC, iborovikov commented on routes/api/contacts.js
> +    const { error } = joiShema.validate(req.body)
Не совсем понял что именно ты имеешь ввиду.
Переделал: оставил в схеме Joi.string().required() для каждого поля, так как с ТЗ написано: 
"Если в body нет каких-то обязательных полей, ..."

2021-10-30 13:19 UTC, iborovikov commented on routes/api/contacts.js
> +    if (contact.status === 'BadRequest') {
Поправил, сделал везде одинаково.

2021-10-30 13:20 UTC, iborovikov commented on routes/api/contacts.js
> +    if (contact.status === 'Contact not found') {
Поправил

2021-10-30 13:20 UTC, iborovikov commented on routes/api/contacts.js
> +        // eslint-disable-next-line no-unreachable
Поправил: заменил switch на if(){}

2021-10-31 08:55 UTC, KirillKulakow commented on routes/api/contacts.js
> +    const { error } = joiShema.validate(req.body)
В Schoology я добавил скрин с дз, суть в том что если я сделаю запрос где в body я напишу только email: "test@email.net" - тогда я получу ошибку, а согласно логике должно поменяться поле имейл

2021-10-31 08:56 UTC, KirillKulakow requested changes
Fix commented fields

2021-11-02 10:35 UTC, iborovikov commented on routes/api/contacts.js
> +    const { error } = joiShema.validate(req.body)
Исправил

2021-11-02 20:14 UTC, KirillKulakow approved these changes

2021-11-04 12:46 UTC, merged