Hw03 mongodb
iborovikov/nodejs-homework-2-rest-api pull request #3
Opened 2021-11-06 18:03 UTC by iborovikov

2021-11-07 14:31 UTC, KirillKulakow commented on models/contact.js
> +const patchShema = Joi.object({
почему только две схемы по валидации?
в прошлой дз было две схемы + в этой дз должна добавится одна

2021-11-07 14:34 UTC, KirillKulakow commented on controllers/contacts/getContactById.js
> +  const id = req.params.contactId
можно упростить до уровня const { contactId } = req.params

2021-11-07 14:36 UTC, KirillKulakow commented on middlewars/controllerWrapper.js
> +const controllerWrapper = (ctrl) => {
можно использовать замыкания для упрощения функции (ctrl) => (res, req, next) => { ...твой код }

2021-11-07 14:37 UTC, KirillKulakow commented on middlewars/validation.js
> +const validation = (schema) => {
также можно использовать замыкания

2021-11-07 14:37 UTC, KirillKulakow requested changes
Need fix

2021-11-08 09:27 UTC, iborovikov commented on controllers/contacts/getContactById.js
> +  const id = req.params.contactId
Изменил во всех контроллерах

2021-11-08 09:47 UTC, iborovikov commented on middlewars/controllerWrapper.js
> +const controllerWrapper = (ctrl) => {
Исправил

2021-11-08 09:59 UTC, iborovikov commented on middlewars/validation.js
> +const validation = (schema) => {
Исправил

2021-11-08 10:42 UTC, iborovikov commented on models/contact.js
> +const patchShema = Joi.object({
Добавил 3-ю схему

2021-11-08 19:45 UTC, KirillKulakow approved these changes

2021-11-08 20:27 UTC, merged