Hw04 auth
iborovikov/nodejs-homework-2-rest-api pull request #6
Opened 2021-11-21 18:12 UTC by iborovikov

2021-11-21 20:50 UTC, KirillKulakow commented on controllers/contacts/getAllContacts.js
> +  console.log(req.query.favorites)
зачем консоль?

2021-11-21 20:51 UTC, KirillKulakow commented on controllers/contacts/getAllContacts.js
> +    const skip = (page - 1) * limit
сделай проверку page и limit на число - если не число - ошибка BadRequest

2021-11-21 20:51 UTC, KirillKulakow commented on controllers/users/getCurrentUser.js
> +  if (!user) {
зачем эта проверка?

2021-11-21 20:54 UTC, KirillKulakow commented on controllers/users/logout.js
> +  if (!user) {
зачем эта проверка?

2021-11-21 20:55 UTC, KirillKulakow commented on middlewars/authenticate.js
> +    const [bearer, token] = req.headers.authorization.split(' ')
если я без авторизации сделаю запрос на список контактов - приложение сломается

2021-11-21 20:56 UTC, KirillKulakow requested changes
Need fix

2021-11-22 09:20 UTC, iborovikov commented on controllers/contacts/getAllContacts.js
> +  console.log(req.query.favorites)
Убрал

2021-11-22 09:20 UTC, iborovikov commented on controllers/contacts/getAllContacts.js
> +    const skip = (page - 1) * limit
Добавил проверку

2021-11-22 09:20 UTC, iborovikov commented on controllers/users/getCurrentUser.js
> +  if (!user) {
Убрал

2021-11-22 09:21 UTC, iborovikov commented on controllers/users/logout.js
> +  if (!user) {
Убрал

2021-11-22 09:27 UTC, iborovikov commented on middlewars/authenticate.js
> +    const [bearer, token] = req.headers.authorization.split(' ')
Не сломается, получишь ошибку 500 с сообщением "Cannot read property 'split' of undefined".
Но мне тоже показалось, что правильней будет выдать ошибку 401, по этому добавил проверку на наличие токена.

2021-11-22 19:03 UTC, KirillKulakow commented
Все ок, но есть рекомендация не по ТЗ
Можешь поправить логику поиска/удаления/обновления контакта по ид
Так как контакты разделены по юзерам, было бы корректней делать поиск не только по ид контакта но и по ид собственника контакта

2021-11-22 19:04 UTC, KirillKulakow approved these changes

2021-11-26 08:27 UTC, merged