Всё без доп. задания
iborovikov/nodejs-homework-2-rest-api pull request #7
Opened 2021-11-27 12:15 UTC by iborovikov

2021-11-27 17:51 UTC, KirillKulakow commented on controllers/users/singup.js
> +  const avatar = gravatar.url(email)
лучше добавить опцию протокола в функции gravatar

2021-11-27 17:53 UTC, KirillKulakow commented on middlewars/uploadAvatar.js
> +  filename: (req, file, cb) => {
было бы неплохо сделать проверку по MIME типу файла

2021-11-27 17:53 UTC, KirillKulakow requested changes
Need fix

2021-11-27 18:22 UTC, iborovikov commented on controllers/users/singup.js
> +  const avatar = gravatar.url(email)
Добавил

2021-11-27 18:48 UTC, iborovikov commented on middlewars/uploadAvatar.js
> +  filename: (req, file, cb) => {
Добавил

2021-11-28 21:40 UTC, KirillKulakow approved these changes

2021-11-29 07:44 UTC, merged